- src/__mocks__/database/campaign.ts
- src/reference/openapi.yml
- src/routes/campaigns/_post/index.spec.ts
- src/routes/campaigns/_post/index.ts
- src/routes/campaigns/checkCampaignRequest/index.ts
- src/routes/campaigns/createCampaign/index.ts
- src/routes/projects/projectId/getProjectById/index.ts
- src/routes/workspaces/getUserWorkspaces/index.ts
- src/routes/workspaces/workspaceId/getUserProjects/index.ts
- src/schema.ts
> Cup 573 campaigns post

- src/__mocks__/database/campaign_meta.ts
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/bugs/bugId/index.spec.ts
- src/routes/campaigns/campaignId/bugs/bugId/index.ts
- src/routes/campaigns/campaignId/bugs/index.spec.ts
- src/schema.ts
- src/utils/bugs/getBugById/index.ts
- src/utils/campaigns/getCampaignBugs/index.ts
- src/utils/campaigns/getTitleRule/index.ts
- src/utils/campaigns/index.ts
- if campaign has title rule in cp meta:
- bug return title, context and contextless_title like this: 
- title: [bug_context] Bug title
- context: bug_context
- contextless_title: Bug title
The previous changes affect the following endpoints:
- GET /campaigns/:CPID/bugs (for each bug)
- GET /campaigns/:CPID/bugs/:BUGID
> UN-15 extract context from bug title

- package.json
- src/__mocks__/database/campaign.ts
- src/routes/campaigns/campaignId/bugs/index.spec.ts
- src/routes/campaigns/campaignId/bugs/index.ts
- src/utils/campaigns/getCampaign/index.ts
- src/utils/campaigns/getCampaignBugs/index.ts
"Should not return refused bugs"
"Should not return need review bugs if option is not enabled"
"Should return need review bugs if option is not enabled but user is admin"
"Should return need review bugs if option is enabled"
> Add status check

- src/features/db/__mocks__/index.ts
- src/routes/index.ts
Return 500 with the error on database malformed sql
> rework: Fail early on db error

- src/reference/openapi.yml
- src/routes/campaigns/campaignId/widgets/_get/index.spec.ts
- src/schema.ts
- src/utils/campaigns/getWidgetBugsByDevice/index.ts
- src/utils/campaigns/getWidgetBugsByUseCase/index.ts
- src/utils/campaigns/getWidgetCampaignProgress/formatProgress.ts
- src/utils/campaigns/getWidgetCampaignProgress/getUseCaseProgress.ts
- src/utils/campaigns/getWidgetCampaignProgress/index.ts
BugsByUsecase:
- Should answer 200 and returns the usecase completion of 12.5
- Should answer 200 and returns the usecase completion of 87.5
- Should NOT returns the usecase completion for the 'not a specific usecase'
BugsByDevice:
- Now include a friendly unique_bugs in addition to the bugs counter (with duplicated)
> UN-134-widget-changes

- src/reference/openapi.yml
- src/routes/campaigns/campaignId/bugs/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugs/bugId/_get/index.spec.ts
- src/routes/campaigns/campaignId/widgets/_get/index.spec.ts
- src/schema.ts
- src/utils/bugs/getBugById/index.ts
- src/utils/campaigns/getCampaignBugs/index.ts
- src/utils/campaigns/getWidgetBugsByDuplicates/index.ts
- Added simpleTitle and prefix to bug schema
- Add usecase meta to bug schema
> Increase usecase details on bug schema

- src/routes/campaigns/campaignId/bugs/_get/index.spec.ts
- src/routes/campaigns/campaignId/widgets/_get/uniqueBugsWidget/getCampaignBugSituation.ts
- src/routes/workspaces/workspaceId/campaigns/_get/index.ts
- src/utils/bugs/getBugById/index.ts
- src/utils/campaigns/getCampaign/index.ts
- src/utils/campaigns/getCampaignBugs/index.ts
- src/utils/campaigns/getWidgetBugsByDevice/index.ts
- src/utils/campaigns/getWidgetBugsByDuplicates/index.ts
- src/utils/campaigns/getWidgetBugsByUseCase/index.ts
we want to show only bugs with publish = 1
> fix(bugs): exclude bugs with publish set to 0

- src/__mocks__/database/bug_type.ts
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/bugTypes/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugTypes/_get/index.ts
- src/schema.ts
- src/utils/campaigns/checkPlatforms/index.ts
"GET - /campaigns/{cid}/bugTypes"
- Should answer 403 if user is not logged in
- Should fail if the campaign does not exist
- Should return 200 if the user is the owner
- Should fail if the user is not the owner
- Should return campaign bugTypes
200 return array of BugTypes
BugTypes: { id: number, name: string }
> UN-262-get-campaign-cid-bugTypes

- src/reference/openapi.yml
- src/routes/campaigns/campaignId/tags/_get/index.spec.ts
- src/routes/campaigns/campaignId/tags/_get/index.ts
- src/schema.ts
get /campaign/CID/tags return:
- all public campaign tags as array of  { tag_id: number, slug: string, display_name: string, is_public?: number },
> Un 313 tags by campaign

- src/__mocks__/database/bug_type_custom.ts
- src/__mocks__/database/companyAdapter.ts
- src/routes/campaigns/campaignId/bugTypes/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugTypes/_get/index.ts
get /campaign/CID/bugTypes return:
- all bugTypes if cp has not custom bugTypes as array of {id: number, name: string}
- custom bugTypes if cp has custom bugTypes as array of {id: number, name: string}
note: all returned bugTybe has property is_enabled = 1
> Un 299 bug type by campaign

- .stoplight/styleguide.json
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/bugs/bugId/_get/index.spec.ts
- src/schema.ts
- src/utils/bugs/getBugMedia/index.ts
- Fixed an issue where the media type returned was different than "image" or "video".
- Changed Media "type" in "mime_type" on schema.
Thanks to @sinatragianpaolo
> Fix bug media type other

- src/__mocks__/database/bug_replicability_custom.ts
- src/__mocks__/database/companyAdapter.ts
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/replicabilities/index.spec.ts
- src/routes/campaigns/campaignId/replicabilities/index.ts
- src/schema.ts
ENPOINT:
- GET /campaigns/CPID/replicabilities
- expected results designed: { id: number, name: string } [ ]
-----------------------------------------------
TEST:
- ✓ Should answer 403 if user is not logged in
- ✓ Should answer 400 if campaign does not exists
- ✓ Should fail if the user is not the owner ( 403 )
- ✓ Should answer 200 if campaign exists and user has access
- ✓ Should return custom replicabilities
- ✓ Should return all campaign replicabilities if campaign has not custom replicability
- ✓ Should return bug replicabilities even if not available in list
> GET-campaign-replicabilities

- src/routes/campaigns/campaignId/usecases/_get/index.spec.ts
- src/routes/campaigns/campaignId/usecases/_get/index.ts
- should return trimmed title
- remove duplicates usecase
- Should return usecases ordered by position asc, id asc
> Get usecases fixes

- src/routes/campaigns/campaignId/usecases/_get/index.spec.ts
- src/routes/campaigns/campaignId/usecases/_get/index.ts
Reverts AppQuality/unguess_api#157
> Revert "feat(get-usecases): should return usecases when is_required = 1"

- src/routes/campaigns/_post/index.spec.ts
- src/routes/campaigns/_post/index.ts
- If an Admin User post a campaign the api does not check che price of CP
- If an Admin User post a campaign the api does not decrease coins in packages
> feat(Should not change coins if post a campaign as admin)

- src/__mocks__/database/seed/profiles.json
- src/__mocks__/jsonwebtoken/index.ts
- src/features/routes/UserRoute.ts
- src/routes/users/me/_get/index.spec.ts
- src/routes/users/me/_get/index.ts
Prevent wrong name display in ui e api calls
> fix(users-me): use tid as key of getProfileName method

- src/routes/campaigns/campaignId/bugs/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugs/_get/index.ts
- src/utils/constants.ts
Feature:
- Order by priority ASC or DESC.
- Handles the query even with default priority.
Tests: 
- Test to check the order
> feat(order by priority): order by priority and test

- src/routes/campaigns/campaignId/bugs/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugs/_get/index.ts
Fixed **/campaigns/{cid}/bugs** endpoint:
- __order__ field ASC/DESC was inverted
> fix(get-bugs): fix priority order flipped

- package.json
- src/features/mail/send/index.ts
- yarn.lock
we have also updated the staging and production instances in order to
include the new env vars
> feat(mail): add sendgrid class in order to send mails

- src/__mocks__/database/companyAdapter.ts
- src/__mocks__/database/customer_invitations.ts
- src/features/routes/Route.ts
- src/features/routes/WorkspaceRoute.ts
- src/reference/openapi.yml
- src/routes/workspaces/workspaceId/_get/index.ts
- src/routes/workspaces/workspaceId/campaigns/_get/index.ts
- src/routes/workspaces/workspaceId/coins/_get/index.spec.ts
- src/routes/workspaces/workspaceId/coins/_get/index.ts
- src/routes/workspaces/workspaceId/users/_get/index.spec.ts
- src/routes/workspaces/workspaceId/users/_get/index.ts
- src/schema.ts
- src/utils/workspaces/getWorkspace/index.ts
endpoint: GET /workspaces/:wid/users
Restituisce la lista di utenti inclusi:
- tester presenti nella user_to_customer
- tester invitati con invito accettato e account attivato
- tester invitati con invito pendig
- tester invitati con invito scaduto
> UGG-7-add-get-workspace-user

- src/routes/campaigns/campaignId/bugs/_get/filters.spec.ts
- src/routes/campaigns/campaignId/bugs/_get/index.ts
🐛 fix(index.ts): change filterBy["customStatus"] to filterBy["customStatuses"]
> 🐛 fix(filters.spec.ts): change filterBy[customStatus] to filterBy[customStatuses]

- src/routes/workspaces/_get/index.spec.ts
- src/routes/workspaces/_get/index.ts
- src/routes/workspaces/_get/useCustomersData.ts
- src/routes/workspaces/_get/useCustomersDataCsmCustom.ts
- src/routes/workspaces/_get/useCustomersDataCsmDefault.ts
- src/routes/workspaces/workspaceId/coins/_get/index.spec.ts
- src/routes/workspaces/workspaceId/coins/_get/index.ts
- src/routes/workspaces/workspaceId/coins/_get/useCustomersData.ts
USE KNEX AND REWORK TO OPENAPI-CLASS FOR:
- get-workspaces
- get-workspaces-coins
> Refactor openapi route to class

- src/routes/workspaces/workspaceId/_get/index.spec.ts
- src/routes/workspaces/workspaceId/_get/index.ts
Restored csm profile pic missing from response
> feat(get-workspace-id): allow workspaces with shared items in it

- package.json
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/findings/findingId/_put/index.spec.ts
- src/routes/campaigns/campaignId/findings/findingId/_put/index.ts
- src/routes/campaigns/campaignId/ux/_get/index.spec.ts
- src/routes/campaigns/campaignId/ux/_get/index.ts
- src/schema.ts
- yarn.lock
- Describe - PUT /campaigns/:campaignId/findings/:findingId
- Should answer 400 if campaign does not exist
- Should answer 400 if campaign does not exist
- Should answer 404 if finding does not exist
- Should answer 403 if the campaign exists but the user has no permissions to see the campaign
- Should answer 200 with the campaign if the user has specific permission to see the campaign
- Should return 404 if the finding is disabled
- Should insert a comment with correct data
- Should update the comment if it already exists for that finding
- Describe - GET /campaigns/:campaignId/ux - With draft only
- Should return only the enabled findings
- Should return the correct findings_ids for each finding
- Should return the all comments for each finding
- Describe - GET /campaigns/:campaignId/ux …
> Insights comments

- package.json
- src/__mocks__/database/companyAdapter.ts
- src/__mocks__/database/custom_status.ts
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/bugs/_get/customStatus.spec.ts
- src/routes/campaigns/campaignId/bugs/_get/index.ts
- src/routes/campaigns/campaignId/bugs/bugId/_get/index.spec.ts
- src/routes/campaigns/campaignId/bugs/bugId/_get/index.ts
- src/routes/campaigns/campaignId/bugs/bugId/_patch/index.spec.ts
- src/routes/campaigns/campaignId/bugs/bugId/_patch/index.ts
- src/routes/campaigns/campaignId/customStatuses/_get/index.ts
- src/schema.ts
- src/utils/constants.ts
- yarn.lock
- Update schema for custom status changes
> Custom status

- src/routes/campaigns/campaignId/customStatuses/_delete/index.spec.ts
- src/routes/campaigns/campaignId/customStatuses/_delete/index.ts
> Fix delete custom status

- src/reference/openapi.yml
- src/routes/projects/projectId/campaigns/_get/index.spec.ts
- src/routes/projects/projectId/campaigns/_get/index.ts
- src/schema.ts
🔧 fix(index.ts): add getOrder and getOrderBy methods to retrieve order and orderBy values from query parameters
> Add-project-pid-campaigns-order

- src/routes/campaigns/campaignId/bugs/bugId/comments/_post/index.spec.ts
- src/routes/campaigns/campaignId/bugs/bugId/comments/_post/index.ts
🔧 fix(index.spec.ts): update URL formatting in comment notification emails
🔧 fix(index.ts): update URL formatting in comment notification emails
> Mock-axios

- package.json
- src/reference/openapi.yml
- src/routes/campaigns/campaignId/videoTags/_get/index.spec.ts
- src/routes/campaigns/campaignId/videoTags/_get/index.ts
- src/routes/campaigns/campaignId/videoTags/_post/index.spec.ts
- src/routes/campaigns/campaignId/videoTags/_post/index.ts
- src/schema.ts
- yarn.lock
- rename endpoint /campaigns/{cid}/videoTags to /campaigns/{cid}/video-tags
- add new verb POST on /campaigns/{cid}/video-tags
> Post a new campaign videotag
